export {default as Header} from './Header'
export {default as Footer} from './Footer'
export {default as Hero} from './Hero'
export {default as Layout} from './Layout'
export {default as Explain} from './Explain'
export {default as WhatTheySay} from './WhatTheySay'
export {default as Band} from './Band'